package cn.xiaoyu.learning.cxfservice.wsinterface.userservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "IUserService", targetNamespace = "http://service.cxfservice.learning.xiaoyu.cn/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface IUserService {


    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://service.cxfservice.learning.xiaoyu.cn/", className = "cn.xiaoyu.learning.cxfservice.wsinterface.userservice.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://service.cxfservice.learning.xiaoyu.cn/", className = "cn.xiaoyu.learning.cxfservice.wsinterface.userservice.GetNameResponse")
    public String getName(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg0
     * @return returns cn.xiaoyu.learning.cxfservice.wsinterface.userservice.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://service.cxfservice.learning.xiaoyu.cn/", className = "cn.xiaoyu.learning.cxfservice.wsinterface.userservice.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://service.cxfservice.learning.xiaoyu.cn/", className = "cn.xiaoyu.learning.cxfservice.wsinterface.userservice.GetUserByIdResponse")
    public User getUserById(
            @WebParam(name = "arg0", targetNamespace = "")
                    long arg0);

}
