package cn.xiaoyu.learning.cxfservice.wsinterface.calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ICalculator", targetNamespace = "http://service.cxfservice.learning.xiaoyu.cn/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ICalculator {


    /**
     * @param arg1
     * @param arg0
     * @return returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://service.cxfservice.learning.xiaoyu.cn/", className = "cn.xiaoyu.learning.cxfservice.wsinterface.calculator.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://service.cxfservice.learning.xiaoyu.cn/", className = "cn.xiaoyu.learning.cxfservice.wsinterface.calculator.SubResponse")
    public double sub(
            @WebParam(name = "arg0", targetNamespace = "")
                    double arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    double arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.cxfservice.learning.xiaoyu.cn/", className = "cn.xiaoyu.learning.cxfservice.wsinterface.calculator.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.cxfservice.learning.xiaoyu.cn/", className = "cn.xiaoyu.learning.cxfservice.wsinterface.calculator.AddResponse")
    public double add(
            @WebParam(name = "arg0", targetNamespace = "")
                    double arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    double arg1);

}
